site_name: KMPShip
site_description: "The Kotlin/Compose Multiplatform boilerplate to quickly ship Android and iOS apps."
site_url: https://kmpship.app/
docs_dir: "docs"

repo_name: "kmp-ship"
repo_url: https://github.com/TweenerLabs/kmp-ship

extra:
  generator: false # Disables the "Made with Material for MkDocs" line
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TweenerLabs/kmp-ship
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/KMPShip

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  custom_dir: overrides
  favicon: assets/favicon.ico
  logo: assets/logo.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.expand
    - navigation.tracking
    - navigation.indexes

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - attr_list
  - md_in_html

nav:
  - "Get started": index.md
  - "Customization": customization.md
  - "App architecture": architecture.md
  - "Features":
      - features/index.md
      - "Authentication": features/authentication.md
      - "Navigation": features/navigation.md
      - "Payments": features/payments.md
      - "Notifications": features/notifications.md
      - "In-App Reviews": features/inappreviews.md
      - "Store publishing": features/publishing.md
